version: '3'

services:

  mysql:
    container_name: mysql8
    image: mysql:8.0.28
    command: mysqld --default-authentication-plugin=mysql_native_password --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    restart: always
    hostname: mysql-host
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: school
      MYSQL_USER: school
      MYSQL_PASSWORD: school
    ports:
      - '3306:3306'
    volumes:
      - './school-api/sql/create-tables.sql:/docker-entrypoint-initdb.d/create-tables.sql'
      - './school-api/sql/initial-load.sql:/docker-entrypoint-initdb.d/initial-load.sql'

  school-api:
    container_name: school-api
    build: ./school-api
    image: school-api
    depends_on:
      - mysql
    hostname: school-api
    restart: always
    ports:
      - 8080:8080
    healthcheck:
      test: "exit 0"
    environment:
      - "SPRING_PROFILES_ACTIVE=dev"

volumes:
  esdata:
    driver: local